stages:
- name: Helm Print
  steps:
  - runScriptConfig:
      image: ubuntu:16.04
      shellScript: |- 
        cat > config <<EOF
        ${KUBE_CONFIG}
        EOF
        cat config
        echo "Done!"
    envFrom:
    - sourceName: kubectl
      sourceKey: config
      targetKey: KUBE_CONFIG
timeout: 60
branch:
  include:
  - master
  exclude:
  - PR*
