stages:
- name: Build
  steps:
  - runScriptConfig:
      image: base/archlinux
      user: www-data
      shellScript: make

- name: Deploy
  steps:
  - runScriptConfig:
      image: ubuntu:16.04
      shellScript: echo "Done!"
timeout: 60
branch:
  include:
  - master
  exclude:
  - PR*
